services:
  mysql_db:
    container_name: mysql_db
    restart: unless-stopped
    env_file: .env
    image: mysql:8.0.35
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./.env:/.env

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file: .env
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
    ports:
      - $PORT:3000
    depends_on:
      - mysql_db
    volumes:
      - ./backend:/src

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data:
